/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package store;
import javax.swing.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

   
    
/**
 *
 * @author Asus
 */
public class TransactionFrame extends javax.swing.JFrame {
     
    public TransactionFrame() {
        initComponents();
        loadProducts();
        
       
    }
    
     private void loadProducts() {
        for (int i = 0; i < Store.productNames.length; i++) {
            productComboBox.addItem(Store.productNames[i]);
        }
    }
     private void completeTransaction() {
        int selectedIndex = productComboBox.getSelectedIndex();

        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(this, "Select a product!");
            return;
        }
        int quantity;
        try {
            quantity = Integer.parseInt(quantityTextField.getText());

            if (quantity <= 0) {
                JOptionPane.showMessageDialog(this, "Quantity must be positive!");
                return;
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter valid quantity!");
            return;
        }
         // Check inventory
        if (quantity > Store.inventoryStocks[selectedIndex]) {
            JOptionPane.showMessageDialog(this, "Insufficient stock!");
            return;
        }

        double subtotal = Store.productPrices[selectedIndex] * quantity;

        // Reduce inventory
        Store.inventoryStocks[selectedIndex] -= quantity;

        // Save to logs
        int index = Store.transactionCount;
        Store.logProductNames[index] = Store.productNames[selectedIndex];
        Store.logQuantities[index] = quantity;
        Store.logCost[index] = subtotal;
        Store.transactionCount++;

        totalLabel.setText("Total: ₱ " + subtotal);

        JOptionPane.showMessageDialog(this, "Transaction Completed!");
    }

        
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransactionFrame.class.getName());

    /**
     * Creates new form TransactionFrame
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        productComboBox = new javax.swing.JComboBox<>();
        quantityTextField = new javax.swing.JTextField();
        computeButton = new javax.swing.JButton();
        purchaseButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logsButton = new javax.swing.JButton();
        inventoryButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        totalLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jScrollPane4.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 390));

        productComboBox.addActionListener(this::productComboBoxActionPerformed);

        quantityTextField.addActionListener(this::quantityTextFieldActionPerformed);

        computeButton.setText("Compute Total");
        computeButton.addActionListener(this::computeButtonActionPerformed);

        purchaseButton.setText("Complete Purchase ");
        purchaseButton.addActionListener(this::purchaseButtonActionPerformed);

        clearButton.setText("Clear");
        clearButton.addActionListener(this::clearButtonActionPerformed);

        jLabel1.setText("Select Product");

        jLabel2.setText("Enter Quantity");

        jLabel3.setText("STORE");

        logsButton.setText("View Logs");
        logsButton.addActionListener(this::logsButtonActionPerformed);

        inventoryButton.setText("View Inventory");
        inventoryButton.addActionListener(this::inventoryButtonActionPerformed);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder("Receipt Preview"));
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inventoryButton)
                            .addComponent(logsButton))
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(518, 518, 518))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(152, 152, 152)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(productComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(computeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(purchaseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(productComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(computeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purchaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inventoryButton)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void quantityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTextFieldActionPerformed
       int selectedIndex = productComboBox.getSelectedIndex();

    try {
        int quantity = Integer.parseInt(quantityTextField.getText());

        if (quantity <= 0) {
            JOptionPane.showMessageDialog(this, "Quantity must be positive!");
            return;
        }

        double total = Store.productPrices[selectedIndex] * quantity;
        totalLabel.setText("Total: ₱ " + total);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Enter valid number!");
    } // TODO add your handling code here:
    }//GEN-LAST:event_quantityTextFieldActionPerformed

    private void computeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeButtonActionPerformed
        int selectedIndex = productComboBox.getSelectedIndex();

    try {
        int quantity = Integer.parseInt(quantityTextField.getText());

        if (quantity <= 0) {
            JOptionPane.showMessageDialog(this, "Quantity must be positive!");
            return;
        }

        double subtotal = Store.productPrices[selectedIndex] * quantity;
        computeButton.setText("Total: ₱ " + subtotal);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Enter valid number!");
    }
    }//GEN-LAST:event_computeButtonActionPerformed

    private void purchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseButtonActionPerformed
    
    int selectedIndex = productComboBox.getSelectedIndex();
    if (selectedIndex == -1) {
        JOptionPane.showMessageDialog(this, "Select a product!");
        return;
    }

    try {
        int quantity = Integer.parseInt(quantityTextField.getText());
        if (quantity <= 0) {
            JOptionPane.showMessageDialog(this, "Quantity must be positive!");
            return;
        }

        if (quantity > Store.inventoryStocks[selectedIndex]) {
            JOptionPane.showMessageDialog(this, "Insufficient stock!");
            return;
        }

        if (Store.transactionCount >= 100) {
            JOptionPane.showMessageDialog(this, "Transaction log is full!");
            return;
        }

        // Fix: Define dateTime BEFORE using it
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        String dateTime = dtf.format(LocalDateTime.now());

        double total = Store.productPrices[selectedIndex] * quantity;

        // Reduce stock and log
        Store.inventoryStocks[selectedIndex] -= quantity;
        int index = Store.transactionCount;
        Store.logProductNames[index] = Store.productNames[selectedIndex];
        Store.logQuantities[index] = quantity;
        Store.logCost[index] = total;
        Store.transactionCount++;

        // Receipt Preview
        jTextArea1.setText(
            "==== RECEIPT ====\n" +
            "Date: " + dateTime + "\n"+
            "Product: " + Store.productNames[selectedIndex] + "\n" +
            "Price: ₱ " + Store.productPrices[selectedIndex] + "\n" +
            "Quantity: " + quantity + "\n" +
            "---------------------\n" +
            "TOTAL: ₱ " + total + "\n" +
            "===================="
        );

        totalLabel.setText("Total: ₱ " + total);
        JOptionPane.showMessageDialog(this, "Transaction Completed!");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid quantity! Please enter a number.");
    }

    }//GEN-LAST:event_purchaseButtonActionPerformed

    private void productComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productComboBoxActionPerformed
        

     // clear existing items
         for (String productName : Store.productNames) {
             productComboBox.addItem(productName);
         }
            int selectedIndex = productComboBox.getSelectedIndex();

    if (selectedIndex >= 0) {
        double price = Store.productPrices[selectedIndex];
        totalLabel.setText("Price: ₱ " + price);
    }
// TODO add your handling code here:
    }//GEN-LAST:event_productComboBoxActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
    quantityTextField.setText("");
    totalLabel.setText("Total: ₱ 0.00");
    jTextArea1.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_clearButtonActionPerformed

    private void logsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logsButtonActionPerformed
    new TransactionLogs().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_logsButtonActionPerformed

    private void inventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButtonActionPerformed
    new InventoryFrame().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryButtonActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TransactionFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton computeButton;
    private javax.swing.JButton inventoryButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton logsButton;
    private javax.swing.JComboBox<String> productComboBox;
    private javax.swing.JButton purchaseButton;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
   
    

  



